# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agendamento.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agendamento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61gendamento.proto\x12\x0b\x61gendamento\"e\n\x12\x41gendamentoRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\t\x12\x11\n\tmedico_id\x18\x02 \x01(\t\x12\x11\n\tdata_hora\x18\x03 \x01(\t\x12\x15\n\respecialidade\x18\x04 \x01(\t\"P\n\x13\x41gendamentoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x16\n\x0e\x61gendamento_id\x18\x02 \x01(\t\x12\x10\n\x08mensagem\x18\x03 \x01(\t2f\n\rAgendaService\x12U\n\x10\x43riarAgendamento\x12\x1f.agendamento.AgendamentoRequest\x1a .agendamento.AgendamentoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agendamento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENDAMENTOREQUEST']._serialized_start=34
  _globals['_AGENDAMENTOREQUEST']._serialized_end=135
  _globals['_AGENDAMENTORESPONSE']._serialized_start=137
  _globals['_AGENDAMENTORESPONSE']._serialized_end=217
  _globals['_AGENDASERVICE']._serialized_start=219
  _globals['_AGENDASERVICE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
